### PR TITLE
Remove constraint that MIMI cannot specify new signalling protocols

### PR DESCRIPTION
**Pull request by ara4n**
Given MIMI is effectively a new signalling protocol, it's very confusing that the charter asserts that MIMI will not standardize new signalling protocols.  Therefore this PR relaxes that constraint, making it clear that existing protocols should be used where possible - but for things like novel interoperable messaging (and possibly VoIP signalling) we may well need more than vanilla SIP/SIMPLE or XMPP.

### CODE REVIEW

**Comment by jdrosen** [comment]
I had interpreted this item in the charter to be referring to voip signaling protocols, and not messaging. I think it is clear we will nede to specify some kind of protocols for messaging. As such I am ok with this change.

**Comment by jdrosen** [comment]
Though perhaps a better way to fix this is to specify that the group will not specify new voip signaling protocols

**Comment by ara4n** [comment]
@coopdanger addressed this in https://github.com/coopdanger/ietf-wg-mimi/commits/d7719326361b40d4d60ef31f1fc473b9a21e1d4d - thanks

**Comment by ara4n** [comment]
(for the record: @jdrosen explained IRL that it's fine to depend on both existing and future-existing VoIP signalling protocols - for instance, if VoIP-over-Matrix a la https://spec.matrix.org/v1.4/client-server-api/#voice-over-ip ended up defined elsewhere in IETF, then it could be in scope as a possible protocol)

**Pull request closed without merging**
